/**
 * @author
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef EVENTS_EVENTS_H
#define EVENTS_EVENTS_H

#include <boost/shared_ptr.hpp>
#include <alcommon/almodule.h>
#include <string>
#include <vector>
#include <qi/os.hpp>

#include <alproxies/almemoryproxy.h>

namespace AL
{
  class ALBroker;
}

class GyroEvents : public AL::ALModule
{
  public:

    GyroEvents(boost::shared_ptr<AL::ALBroker> broker, const std::string& name);

    virtual ~GyroEvents();
 
    /**
    * Will be called at module startup. Declares example event and subscribes to
    * it.
    */
    virtual void init();

    /**
    * Callback function every time the example event is called.
    */
    void callback(const std::string &key, const AL::ALValue &value, const AL::ALValue &msg);
    void AverageTurn(const std::string &key, const AL::ALValue &value, const AL::ALValue &msg);
    /**
    * A very simple function to generate the event.
    */
    void generateEvent(const float& value);

    /**
    * A very simple function to generate the event.
    */
    void generateMicroEvent(const float& value);
    
    void Average();
    
    void timer();

  private:
 
    AL::ALMemoryProxy fMemoryProxy;

    AL::ALValue * fGyroY;
    AL::ALValue fCurrentGyro;
    float fgyro;
    
    std::vector<float> lastvalues;
    
    float ftotal;
    float faverage;
    float foldaverage;
    float datapoints;
    
    qi::os::timeval startTime;
    qi::os::timeval currentTime;
    
    float time;
};



#endif  // EVENTS_EVENTS_H

