/**
 * @author Emilie Wirbel
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef BUMPER_BUMPER_H
#define BUMPER_BUMPER_H

#include <boost/shared_ptr.hpp>
#include <alcommon/almodule.h>
#include <fstream>
#include <string>
#include <qi/os.hpp>
#include <alcommon/alproxy.h>
#include <alproxies/almemoryproxy.h>
#include <alproxies/altexttospeechproxy.h>
#include <althread/almutex.h>
#include "createmodule.h"
namespace AL
{
  class ALBroker;
}

class SubscribeGyro : public AL::ALModule
{
  public:

    SubscribeGyro(boost::shared_ptr<AL::ALBroker> broker, const std::string& name);

    virtual ~SubscribeGyro();

    /** Overloading ALModule::init().
    * This is called right after the module has been loaded
    */
    virtual void init();
    void GyroStart();
	void timer();
    /**
    * This method will be called every time the event RightSubscribeGyroPressed is raised.
    */
    //void onRightSubscribeGyroPressed();
    void onMoveForward(const std::string &key, const AL::ALValue &value, const AL::ALValue &msg);
    void onMoveBackward(const std::string &key, const AL::ALValue &value, const AL::ALValue &msg);

  private:
    AL::ALMemoryProxy fMemoryProxy;
    AL::ALTextToSpeechProxy fTtsProxy;
//   AL::ALProxy genericProxy;
	qi::os::timeval	currentTime, startTime;
	double time;
//	qi::os::timeval start;
//	time_t currentTime, start;
    boost::shared_ptr<AL::ALMutex> fCallbackMutex;
	std::fstream file;
    float fState;
    
    
    qi::os::timeval lastTime;

    float t;

};

#endif  // BUMPER_BUMPER_H

